apiVersion: apps/v1
kind: Deployment 
metadata:
  name: userservice
  namespace: default
spec:
  replicas: 2
  selector:
      matchLabels:
          app: userservice
  template:
      metadata:
          labels:
              app: userservice

      spec:
        containers:
        - name: userservice
          image: kubemaster01.kubernetes.ka.xcore.net:443/userservice:0
          ports:
          - containerPort: 8080
        imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: userservice
  namespace: default
spec: 
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30002
      protocol: TCP
  selector:
    app: userservice
